# Website settings
title: "Your Story Blog"
description: "A place where stories come alive"
author: "Your Name"
avatar: "/assets/img/avatar-icon.png"  # Upload your photo later

# Your website URL
url: "https://yourdomain.com"  # Replace with your actual domain
baseurl: ""

# Social networks usernames (Optional)
social-network-links:
  email: "youremail@gmail.com"
  github: yourusername
  twitter: yourtwitter
  instagram: yourinsta

# Navigation bar links
navbar-links:
  About Me: "aboutme"
  Stories: "stories"
  Contact: "contact"

# Blog settings
paginate: 5
paginate_path: "/page:num/"

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-sitemap
